[tool.poetry]
name = "reactive-bb-backend"
version = "0.1.0"
description = ""
authors = ["fdemian <fdemian@gmail.com>"]
readme = "README.md"
packages = [{include = "reactive_bb_backend"}]

[tool.poetry.dependencies]
python = "^3.11"
ariadne = "0.23.0"
alembic = "1.13.2"
psycopg2-binary = "^2.9.9"
pyjwt = "^2.8.0"
starlette = "0.37.2"
python-multipart = "0.0.9"
gunicorn = "22.0.0"
rauth = "^0.7.3"
aiohttp = "3.9.5"
aiofiles = "24.1.0"
sqlalchemy-utils = "0.41.2"
websockets = "^12.0"
graphql-core = "^3.2.3"
anyio = "4.4.0"
uvicorn = "0.30.1"
pytest = "8.2.2"
pytest-asyncio = "0.23.7"
pytest-cov = "5.0.0"
coverage = "7.5.4"
broadcaster = "^0.2.0"
mypy = "1.10.1"
asyncpg = "^0.29.0"
httpx = "0.27.0"
tomli = "^2.0.1"
sqlalchemy = "2.0.31"
supervisor = "^4.2.5"
requests = "2.32.3"
flake8 = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
init = "api.scripts.initial_config:main"
adduser = "api.scripts.add_user:main"
createdb = "api.scripts.create_database:main"
destroydb = "api.scripts.destroy_database:main"
resetdb = "api.scripts.reset_database:main"
testdata = "api.scripts.insert_test_data:main"
db_upgrade = "alembic upgrade head:main"
db_downgrade = "alembic downgrade base:main"
